version: '3.5'

services:
  db_lunch:
    container_name: db_lunch
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    image: postgres:14.3-alpine
